apiVersion: 1

datasources:
  # VictoriaMetrics as primary datasource for OpenTelemetry metrics
  - name: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      timeInterval: "5s"
