// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("metricsinference")
	ScopeName = "github.com/rbellamy/opentelemetry-inference/processor/metricsinferenceprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
